### PR TITLE
test:415 ->moonseoklee

### PR DESCRIPTION
**Pull request by moonseoklee**
thanks a lot

### CODE REVIEW

**Comment by Suor** [comment]
Can you please remove whitespace changes, it's probably your editor surprising things

**Comment by Suor** [comment]
Thanks for the test

**Comment by Suor** [comment]
Also the test looks quite complicated. Do you experience this issue with simple exclude boy involving m2m?

**Comment by moonseoklee** [comment]
Apologize for whitespaces. I removed it.

Yes. I experienced it with m2m. But i didn't test with exclude other fields(like foreign key). 
If it needed, i will test for other field types

**Comment by moonseoklee** [comment]
Is it a bug? Or is there a test that I need to do more?

**Comment by Suor** [comment]
Looks like a m2m bug. Django had it's own issues with it and cacheops might have its own.

**Comment by moonseoklee** [comment]
> Looks like a m2m bug. Django had it's own issues with it and cacheops might have its own.

Thanks!!

**Comment by moonseoklee** [comment]
@Suor Can I check Django's bug document related to this?

**Comment by Suor** [comment]
Not sure why would I stop you

**Pull request closed without merging**
