### PR TITLE
More lenient way of checking request object

### PR DESCRIPTION
**Pull request by modbender**
More generic way of checking request object

Source: Django view decorator cache.py
https://github.com/django/django/blob/main/django/views/decorators/cache.py

### CODE REVIEW

**Comment by Suor** [comment]
This looks like a very indirect way to check for type. Going duck typing helps though, I should agree. 

BTW, what about the other error you were getting?

**Comment by modbender** [comment]
Working on that, but it will take time. This is just the first necessary step.

**Comment by modbender** [comment]
For the other error, I'm planning on making a plugin package or something that can be used for rest API.
The classes used and working in REST API is way too different.

**Comment by modbender** [comment]
I think this pull can be merged, it's harmless enough and might help someone out there.

**Comment by Suor** [comment]
It is not as innocent as it looks:
1. It is incomplete, so it will make false promises of working and confuse people.
2. It has no tests, so might break silently at some point.

Merging this will require me to support it, which I am not ready to do in this form. Also, ideally it does not belong to cacheops as cacheops better not know about internals of other Django libs.

**Comment by modbender** [comment]
Well the code is directly from official Django source code, so I don't think 1 is true.
About 2, I'm not all that knowledgeable about create tests yet, so I'll leave it to someone who might know or maybe do it later.

**Pull request closed without merging**
