### PR TITLE
Fix clean_dnf sorting issue

### LINKED ISSUE #232: Issue when sorting conjunctions in DNF
Turns out that there is an issue when querying the same field multiple times when one of the query is for `__isnull=True`.

For example, given we have following models:

    class Site(models.Model):
        domain = models.CharField(max_length=127)

    class Article(models.Model):
        site = models.ForeignKey(Site, null=True)

The following query:

    Article.objects.cache().filter(Q(site__isnull=True) | Q(site__in=[site])).filter(site=site)

fails with `TypeError: unorderable types: int() < NoneType()`. The error happens while sorting conjunctions in `clean_dnf` function:

    map(sorted, cleaned)

where `cleaned` in this case is:

    [[('site_id', None), ('site_id', 1)]]

One way to fix this would be to cast values to strings before comparing them, like that:

    map(lambda l: sorted(l, key=lambda x: str(x)), cleaned)

I will submit PR with the above fix and relevant test case in a minute.

### PR DESCRIPTION
**Pull request by michalochman**
Fixes #232

### CODE REVIEW

**Comment by Suor** [comment]
There are several issues with this patch:

1. Solution is inefficient in several ways. Main one is that values are converted to strings anyway in lua, so one can just convert them before sorting.
2. Problem is Python 3 only, so inefficiency for Python 2 users is even less acceptable.
3. Tests are too volumous. You don't need 2 new models, I don't think you even need one, just use one of the basic. Also, there is no need to create objects, this doesn't affect test anyway.

**Comment by michalochman** [comment]
@Suor I will be happy to adjust the patch, but I have no idea what would be the best fix to this problem, any suggestions?

**Comment by Suor** [comment]
Looked into it a bit more and it looks as not a practical issue see my comment in #232. This still could be fixed, though, to handle stupid queries generated by some complicated code. The easiest way is probably to use `str(value)` in `clean_conj()`.

**Comment by michalochman** [comment]
Unfortunately, using `str(value)` in `clean_conj()` causes `test_invalidate_by_boolean` and `test_reverse_fk_same` to fail.

**Comment by Suor** [comment]
This is because you need to prepare obj dict the same way for invalidation.

**Comment by michalochman** [comment]
@Suor I have implemented it according to your guidance and removed unnecessary models from tests. Also, `str` is imported from `builtins` in order for the code to be Python 2-3 compatible. 

What do you think? See my comment in #232 for the real world example of the problem.

**Comment by michalochman** [comment]
Seems that `builtins` is not available on Travis, let me investigate.

**Comment by Suor** [comment]
The point of builtins that you don't need to import them :) Tests fail because in Python 2 builuins module is called `__builtin__`. Not that this matters anyway.

**Comment by michalochman** [comment]
I now see that the project has `six` listed as it's dependencies so installing `future` seems pointless. Should I remove the import altogether and just use whatever `str` is available at runtime?

**Comment by Suor** [comment]
Also, you will run into failing to `str()` unicode data - `.test_114()`.

I think we probably should try an alternative solution - filtering out dups in `clean_dnf()` or `clean_conj()`.

In both cases performance should be tested before accepting anything.

**Comment by michalochman** [comment]
The reason I wanted `str` imported from `builtins` (coming from `future`) was meant to cover the unicode case, see http://python-future.org/compatible_idioms.html#unicode

---

Unless you can guarantee that the function removing duplicates always returns the same value for the following input:

    [[('attname', 'value'), ('attname', None)]]
    [[('attname', None), ('attname', 'value')]]

I am not sure that removing duplicates is a good idea, because they are not really "duplicates". What is unique here is a tuple of `(attname, value)` not just `attname`, don't you think? 

If that function was stable, it would return the first element of the inner list which is either `('attname', 'value')` or `('attname', None)` respectively. If it was not stable, it would return the inner items in arbitrary order.

Anyway, if this is not the issue, I found this benchmark: https://www.peterbe.com/plog/uniqifiers-benchmark and have tested it using `f5` function which was the fasted stable function under benchmark. The code and results are here: https://gist.github.com/michalochman/7d66b3fc92fee3cc519fb98d3d1a4b4c

**Comment by Suor** [comment]
Conjs with duplicate fields and different values are useless, they will never cause invalidation. Dups with same values could be safely deduped with no resulting change in invalidation logic.

So removing dups should:
- completely remove any conj like `[['f1', None], ['f1', 'v'], ['f2', 'v2'], ...]`
- dedupe `[['f1', 'v'], ['f1', 'v'], ['f2', 'v2'], ...]` into `[['f1', 'v'], ['f2', 'v2'], ...]`

**Comment by Suor** [comment]
Returning empty list is a bug. Empty list means empty conj = match all.

**Comment by michalochman** [comment]
What do you mean by

> completely remove any conj like `[['f1', None], ['f1', 'v'], ['f2', 'v2'], ...]`

then?

**Comment by Suor** [comment]
It should be removed from a list of conjs not replaced with empty
conjunction.

**Comment by michalochman** [comment]
Oh, you're right – fixed.

**Pull request merged**
