### PR TITLE
Added code to have the setting CACHE_OPS_KEY - bala

### PR DESCRIPTION
**Pull request by subramanyamVemu**
This is to have a user defined key string or a function that will be added before the key <  userdefined_key >as:xxx or < userdefined_key  >p:xxx 

user has to define a string or a function with CACHE_OPS_KEY

Please let me know your comments

### CODE REVIEW

**Comment by subramanyamVemu** [comment]
A user can override the default key by having the following in settings

def get_key(default_key=None):
    if default_key is None:
        return None
    import datetime
    return datetime.datetime.now().strftime("%Y%m%d%H") + default_key

# assign a function
CACHE_OPS_KEY = get_key

**Comment by subramanyamVemu** [comment]
I am not sure about the key -  conj:xx whether we want to delete the object from memory

**Comment by Suor** [comment]
Not sure what you are trying to do here.

**Comment by Suor** [comment]
Anyway, using separate redis instances is recommended. Using separate redis dbs could be used as compromise.

BTW, your code most probably won't work. There are not only cache keys, but conj keys and schemes. Also keys are also accessed through lua scripts.

**Comment by Suor** [comment]
Closing this since this approach is not going to work and the lack of interest.

**Pull request closed without merging**
