### PR TITLE
Add weak=False to connect

### PR DESCRIPTION
**Pull request by GuillaumeCisco**
Fix https://github.com/Suor/django-cacheops/issues/217

### CODE REVIEW

**Comment by Suor** [comment]
How about writing a falling test?

**Comment by GuillaumeCisco** [comment]
Sorry I don't have time for that.

**Comment by Suor** [comment]
This doesn't look as a right fix. Cacheops doesn't connect local functions via signals but manager methods. This means your code destroys manager (wtf???) and so removes signals, but when new manager is probably created with possibly new signal handlers attached. With this magic happening and `weak=False` you'll get a memory leak because manager won't be freed and more importantly more and more handlers will be attached to same signals running invalidation several time for each event. This will lead to high CPU consumption and over time will hang up everything.

**Comment by GuillaumeCisco** [comment]
Sorry, but I don't have time to investigate more.
I let this to others.
Hope this discovery helps.

**Comment by Suor** [comment]
Looked once more at the code, signals are garanteed to not be installed more than once for single class. So worst case scenario won't happen, but still something weird is happening in your code. It can bite you some day.

**Pull request closed without merging**
