### PR TITLE
Added support for django==1.8rc1

### PR DESCRIPTION
**Pull request by coldmind**

### CODE REVIEW

**Comment by Suor** [comment]
Thanks. Can you add a comment describing a hack, it will help me the day I drop Django 1.7

**Comment by coldmind** [comment]
@Suor, just added the comment.

**Comment by Suor** [comment]
Merged, thanks. I am curious, do you actually use Django 1.8rc1?

**Comment by coldmind** [comment]
@Suor I'm currently working on updating all requirements to make project run on 1.8

**Pull request merged**
