### PR TITLE
Re-raise commit errors

### LINKED ISSUE #427: AtomicMixIn doesn't re-raise commit exceptions
https://github.com/Suor/django-cacheops/blob/ad83e51b6d82ba2bf4820953925ff889e4c4b840/cacheops/transaction.py#L74-L79

If the `__no_money__` object fails to commit the transaction and raises a `DatabaseError`, cacheops silences the exception. This sometimes makes integrity errors hard to discover, since transactions fail to commit without notice.

This `except` block should contain a `raise` operator.

### PR DESCRIPTION
**Pull request by yamnikov-oleg**
Resolves #427 

Let me know if this edit is okay or I should change something :)

### CODE REVIEW

**Comment by Suor** [comment]
Does the changed test fail without raise?

**Comment by Suor** [comment]
Thanks, merged.

**Comment by M1ha-Shvn** [comment]
I've also touched this issue in my production environment, when transactions failing on `COMMIT;` database statement suddenly continued execution instead of raising a `DatabaseError`. When can a release be expected?

**Comment by Suor** [comment]
I will look into it today.

**Comment by Suor** [comment]
Ok, released as 6.1

**Pull request merged**
